on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "docs/**"
jobs:
  test:
    name: Run Integration Tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: Azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Pester
      run: Install-Module -Name Pester -Force
      shell: pwsh
    - name: Execute Tests
      run: Invoke-Pester
      shell: pwsh
      env:
       AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
